# Generated by Django 3.2 on 2021-10-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JanmoUtsavVari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_column='FullName', max_length=250)),
                ('username', models.CharField(db_column='UserName', max_length=250)),
                ('statename', models.CharField(db_column='StateName', max_length=250)),
                ('districtname', models.CharField(db_column='DistrictName', max_length=250)),
                ('taluka_name', models.CharField(db_column='Taluka_Name', max_length=250)),
                ('invoiceno', models.CharField(db_column='InvoiceNo', max_length=250)),
            ],
            options={
                'db_table': 'janmo_utsav_vari',
                'managed': False,
            },
        ),
    ]
