# Generated by Django 3.2 on 2021-10-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnew_table', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='employees',
        ),
    ]
