# Generated by Django 3.2 on 2021-10-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20211008_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_table',
            name='idnew_table',
            field=models.Field(),
        ),
    ]
